# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 22:32
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('type', models.CharField(choices=[('1', 'TECHNOLOGY'), ('2', 'TOOL'), ('3', 'TUTORIAL'), ('4', 'EXAMPLE'), ('5', 'STRATEGY'), ('6', 'DEVELOPMENT'), ('7', 'DISCIPLINE')], max_length=1)),
                ('item_code', models.IntegerField(default=-1)),
                ('version', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'IN REVIEW'), ('2', 'ACCEPTED'), ('3', 'REJECTED'), ('4', 'UNFINISHED')], max_length=1)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Development')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Discipline')),
                ('example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Example')),
                ('images', models.ManyToManyField(to='catalogo.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('description', models.CharField(default='', max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.CharField(max_length=100)),
                ('phone_extension', models.IntegerField(default=0)),
                ('experience_areas', models.ManyToManyField(to='catalogo.ExperienceArea')),
                ('projects', models.ManyToManyField(related_name='member_involved', to='catalogo.Item')),
                ('tools', models.ManyToManyField(to='catalogo.Item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('license_type', models.CharField(max_length=150)),
                ('integration', models.BooleanField(default=False)),
                ('use_restrictions', models.CharField(max_length=500, null=True)),
                ('download_url', models.CharField(max_length=1000, null=True)),
                ('functional_description', models.CharField(default='', max_length=1000)),
                ('operating_systems', models.CharField(default='', max_length=150)),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=1000)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Strategy'),
        ),
        migrations.AddField(
            model_name='item',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology'),
        ),
        migrations.AddField(
            model_name='item',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool'),
        ),
        migrations.AddField(
            model_name='item',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tutorial'),
        ),
        migrations.AddField(
            model_name='example',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Strategy'),
        ),
        migrations.AddField(
            model_name='example',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='tools',
            field=models.ManyToManyField(to='catalogo.Tool'),
        ),
        migrations.AddField(
            model_name='development',
            name='dev_technologies',
            field=models.ManyToManyField(to='catalogo.DevelopmentTechnology'),
        ),
    ]
