# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 18:45
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'catalogo', '0001_initial'), (b'catalogo', '0002_auto_20180321_1027'), (b'catalogo', '0003_auto_20180323_1120'), (b'catalogo', '0004_auto_20180323_1125'), (b'catalogo', '0005_item'), (b'catalogo', '0006_auto_20180323_1523'), (b'catalogo', '0007_auto_20180323_1529'), (b'catalogo', '0008_auto_20180326_1312'), (b'catalogo', '0009_example_url'), (b'catalogo', '0010_auto_20180326_1332'), (b'catalogo', '0011_auto_20180330_1948'), (b'catalogo', '0012_auto_20180401_1651'), (b'catalogo', '0013_auto_20180412_1559'), (b'catalogo', '0014_auto_20180412_1623'), (b'catalogo', '0015_item_status'), (b'catalogo', '0016_developmenttechnology'), (b'catalogo', '0017_auto_20180417_1141'), (b'catalogo', '0018_auto_20180417_1221'), (b'catalogo', '0019_auto_20180417_1417'), (b'catalogo', '0020_auto_20180420_1657'), (b'catalogo', '0021_tool_integration'), (b'catalogo', '0022_auto_20180420_2009'), (b'catalogo', '0023_auto_20180421_1218'), (b'catalogo', '0024_auto_20180421_1220'), (b'catalogo', '0025_auto_20180421_1356'), (b'catalogo', '0026_auto_20180421_1602'), (b'catalogo', '0027_item_author'), (b'catalogo', '0028_auto_20180517_1343')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool')),
                ('description', models.CharField(default=django.utils.timezone.now, max_length=500)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool'),
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('type', models.CharField(choices=[('1', 'TECHNOLOGY'), ('2', 'TOOL'), ('3', 'TUTORIAL'), ('4', 'EXAMPLE')], max_length=1)),
                ('example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Example')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool')),
                ('tutorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tutorial')),
            ],
        ),
        migrations.RemoveField(
            model_name='tool',
            name='technology',
        ),
        migrations.AddField(
            model_name='example',
            name='url',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Strategy'),
        ),
        migrations.AddField(
            model_name='tool',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'TECHNOLOGY'), ('2', 'TOOL'), ('3', 'TUTORIAL'), ('4', 'EXAMPLE'), ('5', 'STRATEGY')], max_length=1),
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='development',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Development'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='item',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('1', 'IN REVIEW'), ('2', 'ACCEPTED'), ('3', 'REJECTED'), ('4', 'UNFINISHED')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DevelopmentTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='development',
            name='dev_technologies',
            field=models.ManyToManyField(to=b'catalogo.DevelopmentTechnology'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'TECHNOLOGY'), ('2', 'TOOL'), ('3', 'TUTORIAL'), ('4', 'EXAMPLE'), ('5', 'STRATEGY'), ('6', 'DEVELOPMENT')], max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to=b'catalogo.Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='tool',
            name='download_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='license_type',
            field=models.CharField(default='None', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='use_restrictions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='functional_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tool',
            name='operating_systems',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.RemoveField(
            model_name='example',
            name='description',
        ),
        migrations.RemoveField(
            model_name='example',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='example',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Strategy'),
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tools', models.ManyToManyField(to=b'catalogo.Tool')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'TECHNOLOGY'), ('2', 'TOOL'), ('3', 'TUTORIAL'), ('4', 'EXAMPLE'), ('5', 'STRATEGY'), ('6', 'DEVELOPMENT'), ('7', 'DISCIPLINE')], max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Discipline'),
        ),
    ]
