# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 15:27
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='example',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool'),
        ),
    ]
