# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 16:20
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180321_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='example',
            name='technology',
        ),
        migrations.AddField(
            model_name='tool',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool'),
        ),
    ]
