# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 16:25
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20180323_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='technology',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
