# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 20:18
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20180323_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('tipo', models.CharField(choices=[('1', 'TECHNOLOGY'), ('2', 'TOOL'), ('3', 'TUTORIAL'), ('4 ', 'EXAMPLE')], max_length=1)),
                ('example', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Example')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool')),
                ('tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tutorial')),
            ],
        ),
    ]
