# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20180323_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='example',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Example'),
        ),
        migrations.AlterField(
            model_name='item',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tool'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tutorial'),
        ),
    ]
