# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20180323_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='technology',
        ),
        migrations.AddField(
            model_name='example',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'TECHNOLOGY'), ('2', 'TOOL'), ('3', 'TUTORIAL'), ('4', 'EXAMPLE')], max_length=1),
        ),
    ]
