# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20180326_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='url',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
