# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_example_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='technology',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology'),
            preserve_default=False,
        ),
    ]
