# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_auto_20180330_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Technology'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'TECHNOLOGY'), ('2', 'TOOL'), ('3', 'TUTORIAL'), ('4', 'EXAMPLE'), ('5', 'STRATEGY')], max_length=1),
        ),
    ]
