# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_auto_20180401_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='STATUS',
            field=models.CharField(choices=[('1', 'IN REVIEW'), ('2', 'ACCEPTED'), ('3', 'REJECTED')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
