# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-14 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='STATUS',
            field=models.CharField(choices=[('1', 'IN REVIEW'), ('2', 'ACCEPTED'), ('3', 'REJECTED'), ('4', 'UNFINISHED')], max_length=1),
        ),
    ]
