# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_auto_20180412_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('1', 'IN REVIEW'), ('2', 'ACCEPTED'), ('3', 'REJECTED'), ('4', 'UNFINISHED')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
