# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-14 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_auto_20180414_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='STATUS',
            new_name='status',
        ),
    ]
