# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-17 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_developmenttechnology'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='dev_technologies',
            field=models.ManyToManyField(to='catalogo.DevelopmentTechnology'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'TECHNOLOGY'), ('2', 'TOOL'), ('3', 'TUTORIAL'), ('4', 'EXAMPLE'), ('5', 'STRATEGY'), ('6', 'DEVELOPMENT')], max_length=1),
        ),
    ]
