# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_auto_20180417_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='catalogo.Image'),
        ),
    ]
