# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_auto_20180417_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='download_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='license_type',
            field=models.CharField(default='None', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='technical_info',
            field=models.CharField(default='None', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='use_restrictions',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
