# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-21 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_tool_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='technical_info',
        ),
        migrations.AddField(
            model_name='tool',
            name='functional_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tool',
            name='operating_systems',
            field=models.CharField(default='', max_length=150),
        ),
    ]
