# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-21 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0023_auto_20180421_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='description',
        ),
        migrations.RemoveField(
            model_name='example',
            name='thumbnail',
        ),
    ]
