# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0025_auto_20180421_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='technology',
        ),
        migrations.AddField(
            model_name='example',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Strategy'),
        ),
    ]
