# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0027_item_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile', models.CharField(max_length=1000)),
                ('experience_years', models.FloatField(default=0)),
                ('phone_extension', models.IntegerField(default=0)),
                ('projects', models.ManyToManyField(to='catalogo.Development')),
                ('tools', models.ManyToManyField(to='catalogo.Tool')),
            ],
        ),
    ]
