# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0032_auto_20180517_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.CharField(max_length=100),
        ),
    ]
