# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0034_experiencearea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='experience_areas',
        ),
        migrations.AddField(
            model_name='member',
            name='experience_areas',
            field=models.ManyToManyField(to='catalogo.ExperienceArea'),
        ),
    ]
