# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0036_remove_member_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tools',
            field=models.ManyToManyField(to='catalogo.Item'),
        ),
    ]
