# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0038_remove_member_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='projects',
            field=models.ManyToManyField(related_name='member_involved', to='catalogo.Item'),
        ),
    ]
